### PR TITLE
Add sera samples

### PR DESCRIPTION
**Pull request by Bernadetadad**
@jbloom could you help me sort out the issues here. I've added sera data and IC50 validations to the pipeline it all runs for the samples I've added but fails because apparently it sees some antibody named `nan`, which I though should mean that I left some empty line or something  in my [barcode_runs](https://github.com/dms-vep/SARS-CoV-2_Delta_spike_DMS_REGN10933/blob/add_sera/data/barcode_runs.csv) file but I can't see any empty lines or cells with spaces in it in there. 

Also, as we are adding sera, we should rename this repo to something like `SARS-CoV-2_Delta_spike_DMS_paper` maybe but I'm not sure how to do that without breaking links.

### CODE REVIEW

**Comment by jbloom** [comment]
@Bernadetadad, the problem is you have empty lines with a `nan` antibody in your file for the validation IC50s. Remove those and it will work.

See line 9 and 17-22 here: https://github.com/dms-vep/SARS-CoV-2_Delta_spike_DMS_REGN10933/blob/add_sera/data/validation_IC50s.csv

**Comment by jbloom** [comment]
Let's table the question of renaming of the repo until we talk in person tomorrow.

**Comment by Bernadetadad** [comment]
:sweat: Sounds good.

**Review by jbloom — APPROVED** [review]
@Bernadetadad, approving so you can merge whenever you want!

**Pull request merged**
